# https://taskfile.dev

################################################################
# バージョン指定
################################################################
version: '3'

################################################################
# タスク定義
################################################################
tasks:
  ##############################################################
  # default という名称のタスクはCLIにてタスク名を
  # 指定されなかった場合に暗黙で実行されるタスク
  ##############################################################
  default:
    cmds:
      # コマンドは複数指定することが出来る
      - echo helloworld
      - echo $PATH
