image: gitpod/workspace-go:latest

tasks:
  - name: install tree command
    command: sudo apt-get update -q && sudo apt-get install -yq tree && sudo apt-get clean
  - name: install go-task
    command: go install github.com/go-task/task/v3/cmd/task@latest

vscode:
  extensions:
    - golang.go
