# https://taskfile.dev

version: '3'

vars:
  KENALL: utf_all.csv

tasks:
  default:
    preconditions:
      - (! test -f {{.KENALL}})
    cmds:
      - wget https://www.post.japanpost.jp/zipcode/{{.KENALL}}
