# https://taskfile.dev

version: '3'

tasks:
  default:
    sources:
      - ./*.md
    method: timestamp
    cmds:
      - echo "CHECKSUM={{.CHECKSUM}}"
      - echo "TIMESTAMP={{.TIMESTAMP}}"
    silent: false
