# https://taskfile.dev

version: "3"

vars:
  PROJ_DIR: ..
  BASE_DIR: "{{.PROJ_DIR}}/01.helloworld"

tasks:
  default:
    cmds:
      - task: files1
      - cmd: echo ------------------------------------------
        silent: true
      - task: files2
  files1:
    dir: '{{.BASE_DIR}}'
    vars:
      ITEMS:
        - README.md
        - Taskfile.yml
    cmds:
      - for: { var: ITEMS }
        cmd: echo {{joinPath .BASE_DIR .ITEM}}
  files2:
    vars:
      ITEMS:
        sh: find {{.PROJ_DIR}} -type f -name '*.yml'
    cmds:
      - for: { var: ITEMS }
        cmd: echo {{.ITEM}}
    silent: true