# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: new-style
      - task: old-style
  new-style:
    #
    # v3.26 より単一コマンドである場合は cmds -> cmd と書かなくても良くなった
    #
    cmd: echo "{{.GREETING}}"
    silent: true
  old-style:
    cmds:
      - cmd: echo "{{.GREETING}}"
        silent: true
